# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhotoEditor SDK Documentation
email: contact@photoeditorsdk.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://docs.photoeditorsdk.com" # the base hostname & protocol for your site
url: "https://imgly.github.io"
baseurl: "/pesdk-docs"
twitter_username: imgly
github_username:  imgly

sass:
  sass_dir: _sass

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist

whitelist:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-sitemap
# include: ['_pages']


Include: ['_features', '_quickstarts', '_guides']

# Build settings
markdown: kramdown

kramdown:
  input: GFM

collections:
  features: 
    output: true
    permalink: /:collection/:path
  quickstarts: 
    output: true
    permalink: /:collection/:path
  guides: 
    output: true
    permalink: /:collection/:path



defaults:
  - scope:
      path: "guides/html5/v3_6"
    values:
      platform: html5
      version: v3_6
      layout: guides/html5/v3_6/content